server:
  port: 8080

spring:
  main:
    banner-mode: off
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  ai:
    mcp:
      server:
        enabled: true
        name: mcp-mysql-server
        version: 0.0.1
        # SYNC or ASYNC
        type: SYNC
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true

# logs on the stdout interfere on protocol operation
logging:
  pattern:
    console:
  file:
    name: ./mcp-mysql-stdio-server.log
  