server:
  port: 8080

spring:
  main:
    banner-mode: off
    web-application-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  ai:
    mcp:
      server:
        enabled: true
        name: my-weather-server
        version: 0.0.1
        # SYNC or ASYNC
        type: SYNC
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true

# logs on the stdout interfere on protocol operation
logging:
  pattern:
    console:
  file:
    name: ./mcp-weather-stdio-server.log
  